version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      target: development
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    environment:
      - FLICKR_API_KEY=${FLICKR_API_KEY}
      - FLICKR_API_SECRET=${FLICKR_API_SECRET}
      - CALLBACK_URL=${CALLBACK_URL}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - REDIS_URL=redis://redis:6379/0
      - PYTHONBREAKPOINT=ipdb.set_trace
      - PYTHONUNBUFFERED=1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    depends_on:
      - redis

volumes:
  redis_data:
