services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - FLICKR_API_KEY=${FLICKR_API_KEY}
      - FLICKR_API_SECRET=${FLICKR_API_SECRET}
      - CALLBACK_URL=${CALLBACK_URL}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
